### ISSUE TITLE
How can I blacklist or whitelist certain URL extensions?

### ISSUE THREAD

**Issue by CaiJiJi** [tijme/not-your-average-web-crawler#2]
Nice Crawler.
I Want to know How to do URL Filtering？
such as www.example.com/news.php?id=1 && www.example.com/news.php?id=2.
I want to cralwer one.
I want to add  Blacklist such as *.jpg *.png. 

```
if os.path.splitext(self.url)[1] not in [blacklist]:
    break
```

Thanks

**Comment by tijme** [comment]
Ok, so if I'm correct you want to whitelist or blacklist certain extensions? For example, blacklist all `*.jpg` and `*.png` URLs. Or whitelist all `*.php` URLs? I would have to implement that feature if you want to.

What you can do however is use the code below to, for example, ignore all `*.jpg` URL's, so they will not be crawled.

```
...

def cb_request_before_start(queue, queue_item):
    if queue_item.request.url.endswith(".jpg"):
        return CrawlerActions.DO_SKIP_TO_NEXT
    else:
        return CrawlerActions.DO_CONTINUE_CRAWLING

options.callbacks.request_before_start = cb_request_before_start

...
```

**Comment by CaiJiJi** [comment]
Thanks. I think this can add to Options.
And I want  URL Deduplication.
Such as 
 www.example.com/news.php?id=1 && www.example.com/news.php?id=2.
I only want to   crawl  www.example.com/news.php?id=1 skip the www.example.com/news.php?id=*.

**Comment by tijme** [comment]
@CaiJiJi Ok. I'm currently working on a feature that does exactly that. It enables you to ignore similar requests. I hope to release it soon.

**Comment by CaiJiJi** [comment]
Thanks. Nice work :)

**Comment by tijme** [comment]
@CaiJiJi I just added the option to prevent scanning similar URLs. See https://tijme.github.io/not-your-average-web-crawler/latest/options_routing.html for more details.

The code below would work for the example you gave.

```
options.routing.minimum_threshold = 10
options.routing.routes = [
    "^(https?:\/\/)?(www\.)?example\.com\/news\.php\?id=[0-9]+$"
]
```
