### ISSUE TITLE
Where is the data dumped?

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [tijme/not-your-average-web-crawler#3]
Where is the data dumped?

**Comment by tijme** [comment]
@WilliamJamesDalrympleWest You can use one of the example scripts I created (for example https://github.com/tijme/not-your-average-web-crawler/blob/master/example_extensive.py).

Then run ``$ python example_extensive.py`` to output the contents to the console. Or run ``$ python -u example_extensive.py > output.log`` to output if to a file.

**Comment by WilliamJamesDalrympleWest** [comment]
@tijme two questions if you would indulge me, 

A) feeding in urls dynamically from a dynamic table > In to what file/section
B) Dumping out results in to databases tables > in what files / section (you mention the above example scripts, i take it there is nothing 'physically' created inside this remit to-date?

Thanks

**Comment by tijme** [comment]
**A)** You can only feed the crawler one URL. The crawler will find all the other URLs itself.

**B)** You can use the `after request finish` [callback](https://tijme.github.io/not-your-average-web-crawler/latest/options_callbacks.html#after-request-finish) to insert the URLs that the crawler found into your database. So something like the example below.

```
def cb_request_after_finish(queue, queue_item, new_queue_items):
    insert_into_database(queue_item.request.url, queue_item.request.method, queue_item.request.data)

    return CrawlerActions.DO_CONTINUE_CRAWLING
```

**Comment by WilliamJamesDalrympleWest** [comment]
Many thanks for clearing that up tijme, loving it :)
