### ISSUE TITLE
Error message with a job finished

### ISSUE THREAD

**Issue by Os3r3um** [tijme/not-your-average-web-crawler#7]
One line summary of the issue here.

Expected behavior
=================

I do expect the crawler do its job and successfully exit. 

Actual behavior
=================

Once the crawler got the job finished I do get this error message:

Steps to reproduce the behavior
=================

I have used this simple python script:

```
# example.py

from nyawc.Options import Options
from nyawc.Crawler import Crawler
from nyawc.CrawlerActions import CrawlerActions
from nyawc.http.Request import Request

def cb_crawler_before_start():
    print("Crawler started.")

def cb_crawler_after_finish(queue):
    print("Crawler finished.")
    print("Found " + str(len(queue.get_all(QueueItem.STATUS_FINISHED))) + " requests.")

def cb_request_before_start(queue, queue_item):
    print("Starting: {}".format(queue_item.request.url))
    return CrawlerActions.DO_CONTINUE_CRAWLING

def cb_request_after_finish(queue, queue_item, new_queue_items):
    print("Finished: {}".format(queue_item.request.url))
    return CrawlerActions.DO_CONTINUE_CRAWLING

options = Options()

options.callbacks.crawler_before_start = cb_crawler_before_start # Called before the crawler starts crawling. Default is a null route.
options.callbacks.crawler_after_finish = cb_crawler_after_finish # Called after the crawler finished crawling. Default is a null route.
options.callbacks.request_before_start = cb_request_before_start # Called before the crawler starts a new request. Default is a null route.
options.callbacks.request_after_finish = cb_request_after_finish # Called after the crawler finishes a request. Default is a null route.

crawler = Crawler(options)

target = raw_input("[-] Target please:= ")

crawler.start_with(Request(target))

```

Error message: 

```
Crawler finished.
global name 'QueueItem' is not defined
Traceback (most recent call last):
  File "/root/Desktop/attack_platform_combined/attack_platform_2/recon/crawler/not-your-average-web-crawler/nyawc/Crawler.py", line 208, in __crawler_finish
    self.__options.callbacks.crawler_after_finish(self.queue)
  File "crawler.py", line 13, in cb_crawler_after_finish
    print("Found " + str(len(queue.get_all(QueueItem.STATUS_FINISHED))) + " requests.")
NameError: global name 'QueueItem' is not defined
```
Is there anything which I can do / it can be done to have this fixed up? 

Thanks!

**Comment by tijme** [comment]
Hello @Os3r3um,

Thank you for the extensive report. I think you need to import the `QueueItem` at the top of your file.

```from nyawc.QueueItem import QueueItem```

This import should be available across all the N.Y.A.W.C examples. If you copied this piece of code from somewhere, could you let me know where you found it?

Thanks.

**Comment by Os3r3um** [comment]
Hi, thanks for the tip. 

I got the original code from here: 

https://tijme.github.io/not-your-average-web-crawler/latest/getting_started.html

Also, do you have a docker version of this? It will be simply amazing if this crawler would have a docker version. :)

**Comment by tijme** [comment]
At the moment I don't have a Docker version of N.Y.A.W.C because I don't use Docker myself.

But feel free to do a merge request.
