### ISSUE TITLE
requirements.txt has some problems

### ISSUE THREAD

**Issue by Lin-Kevin** [tijme/not-your-average-web-crawler#8]
beautifulsoup4==4.6.0
lxml==4.0.0
requests==2.18.4
requests_toolbelt==0.8.0
sphinx==1.5.5
sphinx-better-theme==0.13--------------->here may be 0.1.5? there is no 0.13 version
sphinxcontrib-napoleon==0.6.1

And the same problem in nyawc.egg-info/requires.txt

**Comment by tijme** [comment]
It looks like version 0.13 was deleted. Does it work with 0.15?

**Comment by Lin-Kevin** [comment]
Yes, I changed  "sphinx-better-theme==0.13"  to "sphinx-better-theme==0.1.5" then it can be installed successfully

**Comment by tijme** [comment]
Thanks for the update, I just pushed a fix to the master branch. I will be releasing the new version on PyPi tonight.
